### ISSUE TITLE
 BAD RESPONSE 500 from https://beta.interieur.gouv.fr/candilib/api

### ISSUE THREAD

**Issue by yassinelyoumni** [tritus/candilibre#26]
Hello,

Je viens d'installer Candilibre, j'arrive à l'exécuter sur Windows. Par contre même avec un lien valide (Tester sur le navigateur) l'appli me retourne toujours le même message d'erreur 500.

PI : j'ai ajouté la ville Saint Priest dans le 69, et j'ai essayé avec SAINT PRIEST et SAINT_PRIEST.

Avez-vous eu ce problème ? Merci d'avance pour votre aide.

--------------------
Logs : 

19:58:50 - Début de la recherche avec les parametres suivants :
  date minimum : 12/01/21
  villes : [SAINT_PRIEST]

19:58:50 - Oups, une erreur inconnue est arrivée : services.api.client.errors.CandilibreClientBadResponseException: BAD RESPONSE 500 from https://beta.interieur.gouv.fr/candilib/api/v2/candidat/places?geoDepartement=69&nomCentre=SAINT_PRIEST : {"isTokenValid":false,"message":"Votre lien de connexion n'est pas valide, veuillez en demander un autre via le bouton \"Déjà inscrit\"","success":false}

**Comment by Youssef-chaneb** [comment]
Hello @yassinelyoumni ,

J'ai vu que tu as fermé l'issue, est-ce que tu as pu trouver une solution ? Je rencontre le même souci.

Merci d'avance pour ton aide !

**Comment by yassinelyoumni** [comment]
Salut @Youssef-chaneb

Malheureusement non, j'ai abandonné l'utilisation de l'outil 😒
