### ISSUE TITLE
Use x_user_id in calls

### ISSUE THREAD

**Issue by tritus** [tritus/candilibre#9]
Candilib api have been updated. We should now send the user id as header.
Related PR : https://github.com/LAB-MI/candilibV2/pull/1306

Solution : we should make a call to `verify-token` with the token and get the id from the header in the response.

**Comment by nicksauca** [comment]
this id is constant, and you can get it from jwt token, no need in verify-token

**Comment by tritus** [comment]
Right! thanks! I feel quite bad I did not even tried to decode the token!
